# sefaz_integration/exceptions.py

class CertificateError(Exception):
    """Exceção lançada quando há falha no processamento de certificados."""
    pass
